### ISSUE TITLE
Looking directly/angled up and swinging causes the shovel to hit the monitor camera

### ISSUE THREAD

**Issue by dopadream** [Rocksnotch/shovelFix#1]
Ignore the different swing sound, its a mod I'm working on with my girlfriend

https://github.com/Rocksnotch/shovelFix/assets/68942129/12481eae-70a6-46d4-9547-cbfb6650460e

**Comment by dopadream** [comment]
Please let me know if this is a conflict with another mod; though I am 90% sure it isn't.

**Comment by Rocksnotch** [comment]
Unfortunately, I believe this is a base game issue. The shovel is hitting the camera directly above you, and that camera is the camera that watches you on the monitor. Without messing up the screen color heavily, this is an unfortunate side effect of the camera being on the same raycast layer as other physical objects in the game.

**Comment by dopadream** [comment]
> Unfortunately, I believe this is a base game issue. The shovel is hitting the camera directly above you, and that camera is the camera that watches you on the monitor. Without messing up the screen color heavily, this is an unfortunate side effect of the camera being on the same raycast layer as other physical objects in the game.

thanks for the info! players typically won't be swinging up that high anyways so

**Comment by Rocksnotch** [comment]
> > Unfortunately, I believe this is a base game issue. The shovel is hitting the camera directly above you, and that camera is the camera that watches you on the monitor. Without messing up the screen color heavily, this is an unfortunate side effect of the camera being on the same raycast layer as other physical objects in the game.
> 
> thanks for the info! players typically won't be swinging up that high anyways so

of course, not a problem. You should still be able to hit things when you are looking up, its just that if there is nothing else it will hit the camera. Been trying to work on a fix for this but otherwise it seems like a vanilla issue.
